[server] # IRAN, Local
bind_addr = "0.0.0.0:3080" # Address and port for server to listen (mandatory).
transport = "ws"           # Protocol ("tcp" or "tcpmux" or "ws", optional, default: "tcp").
token = "your_token"       # Authentication token (optional).
nodelay = false            # Enable TCP_NODELAY (optional, default: false).
channel_size = 2048        # Tunnel channel size. Excess connections are discarded. Only for tcp and ws mode (optional, default:2048).
connection_pool = 8        # Number of pre-established connections. Only for tcp mode (optional, default: 8).
mux_session = 2            # Number of mux sessions for tcpmux.  (optional, default: 1).
log_level = "info"         # Log level ("panic", "fatal", "error", "warn", "info", "debug", "trace", optional, default: "info").

ports = [ # Local to remote port mapping in this format LocalPort=RemotePort (mandatory).
	"4000=5201",
	"4001=5201",
]
